version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: zht-miningcore_web_1
      APP_PORT: 8080

  server:
    image: theretromike/miningcore
    user: "1000:1000"
    init: true
    volumes:
      - /home/umbrel/.miningcore/coins.json:/app/build/coins.json
      - /home/umbrel/.miningcore/config.json:/app/config.json
    ports:
      - 6001-6025:6001-6025
      - 6201-6225:6201-6225
      - 6301-6325:6301-6325
      - 6401-6425:6401-6425
      - 4000:4000

  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - server
