version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: zht-bchii-node_web_1
      APP_PORT: 8080

  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node

  node:
    image: theretromike/nodes:bitcoincashii
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.bitcoincashii:/root/.bitcoin
    ports:
      - 9010:9010    # RPC
      - 7010:7010    # ZMQ
      - 8340:8340    # P2P
    entrypoint: "bitcoincashIId -printtoconsole -server -prune=550 -zmqpubhashblock=tcp://127.0.0.1:7010 -rpcbind=0.0.0.0 -rpcport=9010 -rpcallowip=0.0.0.0/0 -port=8340 -rpcuser=zahidliono -rpcpassword=Idd=9108 -maxtipage=504576000"
