version: "3.7"

services:

  app_proxy:
    depends_on:
      - web
    environment:
      APP_HOST: ${APP_ID}_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: umbrel
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umbrel -d umbrel"]
      interval: 10s
      timeout: 5s
      retries: 5

  init_pgadmin_perms:
    image: busybox:1.36
    restart: "no"
    command: >
      sh -lc "
        mkdir -p /var/lib/pgadmin/sessions /var/lib/pgadmin/storage &&
        chown -R 5050:5050 /var/lib/pgadmin &&
        chmod -R 750 /var/lib/pgadmin
      "
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin

  web:
    image: dpage/pgadmin4:latest
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      init_pgadmin_perms:
        condition: service_completed_successfully
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umbrel.local
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
      PGADMIN_LISTEN_PORT: "80"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["local","umbrel.local"]'
      PGADMIN_CONFIG_GLOBALLY_DELIVERABLE: "False"
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: "1"
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: "0"
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
